### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Exception\ConnectException::hasResponse() 

### ISSUE THREAD

**Issue by zhmm** [aliyunmq/mq-http-php-sdk#5]
[2020-12-15 03:52:07 *26589.0]	ERROR	php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Exception\ConnectException::hasResponse() in /data/wwwroot/xxx-core/vendor/aliyunmq/mq-http-sdk/MQ/Responses/MQPromise.php:45
Stack trace:
#0 /data/wwwroot/xxx-core/vendor/aliyunmq/mq-http-sdk/MQ/Http/HttpClient.php(94): MQ\Responses\MQPromise->wait()
#1 /data/wwwroot/binlog-es-core/vendor/aliyunmq/mq-http-sdk/MQ/MQConsumer.php(84): MQ\Http\HttpClient->sendRequest(Object(MQ\Requests\ConsumeMessageRequest), Object(MQ\Responses\ConsumeMessageResponse))
#2 /data/wwwroot/xxx-core/Task/Binlog.php(20): MQ\MQConsumer->consumeMessage(16, 1)
#3 /data/wwwroot/xxx-core/sw.php(94): xx\Task\Binlog::getData(16, Array, true)
#4 /data/wwwroot/xxx-core/sw.php(76): Server->getBinlogData(0)
#5 {main}
  thrown in /data/wwwroot/xxx-core/vendor/aliyunmq/mq-http-sdk/MQ/Responses/MQPromise.php on line 45

**Comment by tianc0209** [comment]
注释掉 vendor/aliyunmq/mq-http-sdk/MQ/Http/HttpClient.php 144到146行,或者修改 vendor/aliyunmq/mq-http-sdk/MQ/Config.php的超时配置 35秒那个配置,我这注释掉后正常报错就是这个超时导致的

**Comment by tianc0209** [comment]
注释掉就那三行能解决

> [2020-12-15 03:52:07 *26589.0] ERROR php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Exception\ConnectException::hasResponse() in /data/wwwroot/xxx-core/vendor/aliyunmq/mq-http-sdk/MQ/Responses/MQPromise.php:45
> Stack trace:
> #0 /data/wwwroot/xxx-core/vendor/aliyunmq/mq-http-sdk/MQ/Http/HttpClient.php(94): MQ\Responses\MQPromise->wait()
> #1 /data/wwwroot/binlog-es-core/vendor/aliyunmq/mq-http-sdk/MQ/MQConsumer.php(84): MQ\Http\HttpClient->sendRequest(Object(MQ\Requests\ConsumeMessageRequest), Object(MQ\Responses\ConsumeMessageResponse))
> #2 /data/wwwroot/xxx-core/Task/Binlog.php(20): MQ\MQConsumer->consumeMessage(16, 1)
> #3 /data/wwwroot/xxx-core/sw.php(94): xx\Task\Binlog::getData(16, Array, true)
> #4 /data/wwwroot/xxx-core/sw.php(76): Server->getBinlogData(0)
> #5 {main}
> thrown in /data/wwwroot/xxx-core/vendor/aliyunmq/mq-http-sdk/MQ/Responses/MQPromise.php on line 45

注释掉就那三行能解决
